export const LABELS: string[] = [
    "NOM",
    "ACCIDENT",
    "ACCIDENT DE VOITURE",
    "APPELER",
    "BAGARRE",
    "BIEN",
    "BLANC",
    "BLEU",
    "CADEAU",
    "CHAISE",
    "COMIQUE",
    "COMMENT",
    "CONCENTRE-TOI",
    "CRAYON",
    "DIFFICILE",
    "DORMIR",
    "DUR",
    "D\u00c9SOL\u00c9",
    "EAU",
    "ENTENDANT",
    "FAMILLE",
    "FOOTBALL",
    "FROID",
    "GARDIEN DE BUT",
    "GUERRE",
    "JUS",
    "LION",
    "MAL",
    "MAMAN",
    "MARRON",
    "MENDIANT",
    "MERCI",
    "MOTO",
    "NE PAS SAVOIR",
    "NOIR",
    "OUBLIER",
    "PAIN",
    "PAPA",
    "PAS",
    "PEU IMPORTE",
    "POLICE",
    "POURQUOI",
    "PROBL\u00c8ME",
    "P\u00c8RE NOEL",
    "RADIO",
    "ROUGE",
    "R\u00c9GION",
    "S'ENTRAINER",
    "SAISONS",
    "SE LAVER",
    "SE MOQUER",
    "SEPT",
    "SIGNER MALADROITEMENT",
    "SIGNER MALADROITEMENT_V2",
    "SOURD",
    "TAXI",
    "TIGRE",
    "T\u00caTU",
    "T\u00caTU_V2",
    "VERT",
    "VITE",
    "VOITURE",
    "VOL",
    "\u00c9COLE"
];